version: '3.9'

services:
  api:
    image: nikanurov1/mlops:v1.0
    container_name: api
    restart: always
    ports:
      - "8877:7755"  
    volumes:
      - ./src:/app/src  
      - ./api.py:/app/api.py
      - ./init.sh:/app/init.sh